# Generated by Django 3.0.5 on 2020-05-03 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('owner', 'email')},
        ),
    ]
